In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import string
from sklearn.model_selection import train_test_split

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
input_files = [
  'edgar_allan_poe.txt',
  'robert_frost.txt',
]

In [ ]:
# collect data into lists
# collect our data into lists for this experiment.We'll be treating each line as an input sample.
input_texts = []
labels = []

#when you loop through a file line by line in Python, It includes the new line character at the end 
#rstrip call will remove the new line since it's not needed.
# The final step is to append this text to our list of input texts and to append the label to our list of labels
for label, f in enumerate(input_files):
    print(f"{f} corresponds to label {label}")
    
    for line in open(f):
        line = line.rstrip().lower() 
        if line:                #to check if an blank line is present or not
            # remove punctuation
            line = line.translate(str.maketrans('', '', string.punctuation))

            input_texts.append(line)
            labels.append(label)

edgar_allan_poe.txt corresponds to label 0
robert_frost.txt corresponds to label 1


In [ ]:
labels, input_texts

([0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,


In [ ]:
train_text, test_text, Ytrain, Ytest = train_test_split(input_texts, labels)

In [ ]:
len(Ytest), len(Ytrain)

(540, 1618)

In [ ]:
train_text[:5] , Ytrain[:5]

(['so suddenly i flung the door wide on him',
  'rights right and the temptation to do right',
  'shall give his undivided time',
  'in the ultimate climes of the pole ',
  'i dont remember why i ever cared'],
 [1, 1, 0, 0, 1])

In [ ]:
# The next step will be to convert our text into integers, as you recall these will be indexes into the markov matrices 
# we are about to define.
# We'll begin by setting idx to one which will act as our current index as we loop through the text.
# We'll also initialize a word to index dictionary with one entry, which maps the unknown token to zero.
# Basically, this will never be used for the train set, but it may be used for the test, If the test set contains words 
# that do not appear in the train set.

In [ ]:
idx = 1
word2idx = {'<unk>' : 0}

In [ ]:
# The next step is to loop through our train text in order to populate where idx inside the loop will begin by splitting 
# the text into tokens.
for text in train_text:
    tokens = text.split()
    for token in tokens:
        if token not in word2idx:
            word2idx[token] = idx
            idx += 1

In [ ]:
word2idx

{'<unk>': 0,
 'so': 1,
 'suddenly': 2,
 'i': 3,
 'flung': 4,
 'the': 5,
 'door': 6,
 'wide': 7,
 'on': 8,
 'him': 9,
 'rights': 10,
 'right': 11,
 'and': 12,
 'temptation': 13,
 'to': 14,
 'do': 15,
 'shall': 16,
 'give': 17,
 'his': 18,
 'undivided': 19,
 'time': 20,
 'in': 21,
 'ultimate': 22,
 'climes': 23,
 'of': 24,
 'pole': 25,
 'dont': 26,
 'remember': 27,
 'why': 28,
 'ever': 29,
 'cared': 30,
 'tempted': 31,
 'her': 32,
 'out': 33,
 'gloom': 34,
 'albeit': 35,
 'he': 36,
 'soared': 37,
 'with': 38,
 'an': 39,
 'undaunted': 40,
 'wing': 41,
 'there': 42,
 'is': 43,
 'our': 44,
 'wildest': 45,
 'mount': 46,
 'a': 47,
 'headless': 48,
 'horse': 49,
 'all': 50,
 'who': 51,
 'owe': 52,
 'thee': 53,
 'most': 54,
 'whose': 55,
 'gratitude': 56,
 'ah': 57,
 'we': 58,
 'safely': 59,
 'may': 60,
 'trust': 61,
 'its': 62,
 'gleaming': 63,
 'set': 64,
 'off': 65,
 'briskly': 66,
 'for': 67,
 'slow': 68,
 'thing': 69,
 'drawn': 70,
 'into': 71,
 'town': 72,
 'about': 73,
 'this': 74,
 'cel

In [ ]:
len(word2idx)

2485

In [ ]:
# The next step is to convert this data into integer format, this is what we need to index our A our pie.
# first step will be to create two empty lists, which we will use to store the results. loop through the train tracks 
# inside the loop will begin by again splitting the text to do tokenisation. use a list comprehension to map each token
# to its corresponding text.The result of this will be a list of integers representing one line of a poem.

# It's possible that not every word in the test set appears in the trains there, so we can't naively try to index the 
# word to dictionary. we'll use the get function and will ensure that we always return a default value of zero this 
# corresponds to the unknown token.
train_text_int = []
test_text_int = []

for text in train_text:
    tokens = text.split()
    line_as_int = [word2idx[token] for token in tokens]
    train_text_int.append(line_as_int)
    
for text in test_text:
    tokens = text.split()
    line_as_int = [word2idx.get(token, 0) for token in tokens]
    test_text_int.append(line_as_int)
    

In [ ]:
train_text_int[100:105], test_text_int[100:105]

([[50, 401, 124, 47, 402, 403],
  [5, 234, 145, 146, 235, 12, 236],
  [24, 5, 98, 404, 287, 405, 43, 5, 406],
  [407, 73, 47, 346, 144, 408],
  [106, 409, 14, 92, 21, 410, 411, 21, 410]],
 [[205, 487, 5, 249, 3, 721, 162, 324, 5, 264],
  [5, 264, 265, 14, 266],
  [0, 33, 12, 0, 798, 18, 916, 0],
  [0, 107, 5, 770, 771, 24, 757],
  [579, 0, 181, 0, 227, 47, 2309, 0]])

In [ ]:
# we're ready to build our A and pie matrices which represent the markov model.Since we have two classes, 
# we'll have two A's and two pies. The first step is to assign the length of word to idx to a variable called V.
# initialize A0, Pi zero A1 and PI one. initialized each of these arrays to all ones. 
# The reason for this is we're going to be using add one smoothing. So these ones are the initial fake counts 
# for each initial word and each transition. The next step will be to add the rest of the counts from the actual text.

V = len(word2idx)

A0 = np.ones((V,V))
pi0 = np.ones(V)

A1 = np.ones((V,V))
pi1 = np.ones(V)

In [ ]:
# build a function to create calculate the counts of each transition
# going to take in three arguments the text for the specific class and the pointer to A and pie.
# because A and pi objects, any modifications we made to them inside this function will be remembered outside the function also
# the data we pass in will be of only single class at a time

# compute counts for A and pi

def compute_counts(text_as_int, A, pi):
    for tokens in text_as_int:
        last_idx = None
        for idx in tokens:
            if last_idx == None:
                # it is the first word in the sentence
                pi[idx] += 1
                
            else:
                # the last word exists, so count a transition
                A[last_idx, idx] += 1
            
            # update last idx
            last_idx = idx
            
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 0], A0, pi0)
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 1], A1, pi1)

In [ ]:
# at present the A and pi only have counts but we need probability
# normalize A and pi so they are valid probability matrices
# convince yourself that this is equivalent to the formulas shown before
# each row of A must sum to one.
# keepthem equals true, ensures that the sum is still two dimensional, which is required for the division to broadcast correctly 
# in Numpy for PI. For pi There is no need to do this since it's just a 1D array.

A0 /= A0.sum(axis=1, keepdims=True)
pi0 /= pi0.sum()

A1 /= A1.sum(axis=1, keepdims=True)
pi1 /= pi1.sum()

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [ ]:
# log A and pi since we don't need the actual probs
logA0 = np.log(A0)
logpi0 = np.log(pi0)

logA1 = np.log(A1)
logpi1 = np.log(pi1)

In [ ]:
# The next step is to compute the priors will begin by counting how many samples belong to class zero and class 1
# compute priors
count0 = sum(y == 0 for y in Ytrain)
count1 = sum(y == 1 for y in Ytrain)
total = len(Ytrain)
p0 = count0 / total
p1 = count1 / total
logp0 = np.log(p0)
logp1 = np.log(p1)
p0, p1

(0.3442521631644005, 0.6557478368355995)

In [ ]:
# we can see that P0 is about 33 percent and P1 is about sixty six percent because of this,it wouldn't make sense 
# to use the maximum likelihood method. Instead, we should look at the posterior, which corresponds to the map method.
# Note also that because the classes are slightly imbalanced, we may want to use a metric other than the accuracy to
# evaluate a classifier.

In [ ]:
# build a classifier
class Classifier:
    def __init__(self, logAs, logpis, logpriors):
        self.logAs = logAs
        self.logpis = logpis
        self.logpriors = logpriors
        self.K = len(logpriors) #no of classes
    
#     The next step is to define a function called compute log likelihood, this will take as input a line
#     of text represented by a list of integers and a class. the class tells us which Markov model to use 
#     since we have one for every class inside the function will begin by retrieving log and log pi, by indexing 
#     our lists by the class.
    def _compute_log_likelihood(self, input_, class_):
        logA = self.logAs[class_]
        logpi = self.logpis[class_]
        
        last_idx = None
        logprob = 0
        for idx in input_:
            if last_idx is None:
                #the first token
                logprob += logpi[idx]
                
            else:
                logprob += logA[last_idx, idx]
                
            #update last idx
            last_idx = idx
        return logprob
#    The next step is to define the predict function, the input into this function as the list of input sequences 
#     inside the function will begin by initializing an array to store the predictions.The next step is to loop through 
#     each input note that we use enumerate so that we get the index as well.Inside the loop, we compute the posterior for
#     each class using a list comprehension.This will give us a list of posteriors one for each class.The next step is to
#     obtain a prediction, which is simply the ARG max of the list of posteriors.
    def predict(self, inputs):
        predictions = np.zeros(len(inputs))
        
        for i, input_ in enumerate(inputs):
            posteriors = [self._compute_log_likelihood(input_, c) + self.logpriors[c] for c in range(self.K)]
            pred = np.argmax(posteriors)
            predictions[i] = pred
        
        return predictions
            

In [ ]:
# each array must be in order since classes are assumed to index these lists
clf = Classifier([logA0, logA1], [logpi0, logpi1], [logp0, logp1])

In [ ]:
Ptrain = clf.predict(train_text_int)

In [ ]:
Ptrain

array([1., 1., 0., ..., 0., 1., 1.])

In [ ]:
Ptrain = clf.predict(train_text_int)
print(f"Train acc: {np.mean(Ptrain == Ytrain)}")

Train acc: 1.0


In [ ]:
Ptest = clf.predict(test_text_int)
print(f"Test acc: {np.mean(Ptest == Ytest)}")

Test acc: 0.8166666666666667


In [ ]:
from sklearn.metrics import confusion_matrix, f1_score

In [ ]:
cm = confusion_matrix(Ytrain, Ptrain)
cm

array([[ 557,    0],
       [   0, 1061]], dtype=int64)

In [ ]:
cm_test = confusion_matrix(Ytest, Ptest)
cm_test

array([[ 95,  70],
       [ 29, 346]], dtype=int64)

In [ ]:
f1_score(Ytrain, Ptrain)

1.0

In [ ]:
f1_score(Ytest, Ptest)

0.8748419721871049