In [ ]:
import numpy as np
import pandas as pd
import nltk

from nltk import word_tokenize

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
movies = pd.read_csv('C:/Users/Stavan/Documents/PYTHON/DATA SCIENCE PROJECTS/MOVIE RECOMMENDER/tmdb_5000_movies.csv')
movies = pd.read_csv('bbc-text.csv')
# movies.head()

FileNotFoundError: ignored

In [ ]:
credits = pd.read_csv('C:/Users/Stavan/Documents/PYTHON/DATA SCIENCE PROJECTS/MOVIE RECOMMENDER/tmdb_5000_credits.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# movies['overview'].to_string() 
# for i in movies['overview']:
#     print(i.types())
    
movies.dropna(inplace=True)
movies.shape

(2225, 2)

In [ ]:
# word_to_index
# convert documents to series of ints/ids/indices
idx = 0
word2idx = {}
tokenized_docs = []
doc_as_int = []
for doc in movies['text'] :
    words = word_tokenize(doc.lower())
    doc_as_int = []
    for word in words:
        if word not in word2idx:
            word2idx[word] = idx
            idx += 1
#             for later
        doc_as_int.append(word2idx[word])
    tokenized_docs.append(doc_as_int)
    
print(tokenized_docs)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
#reverse mapping
# idx2word = {v:k for k, v in word2idx.items()} #this is for set representation
# this is somewhat inefficient because we're using a dictionary data structure, even though our 
# indices are only integers from zero up to the vocabulary size.It would be more efficient to store a list instead.
idx2word = []
for k, v in word2idx.items():
    idx2word.insert(v, k)

In [ ]:
idx2word

['tv',
 'future',
 'in',
 'the',
 'hands',
 'of',
 'viewers',
 'with',
 'home',
 'theatre',
 'systems',
 'plasma',
 'high-definition',
 'tvs',
 'and',
 'digital',
 'video',
 'recorders',
 'moving',
 'into',
 'living',
 'room',
 'way',
 'people',
 'watch',
 'will',
 'be',
 'radically',
 'different',
 'five',
 'years',
 'time',
 '.',
 'that',
 'is',
 'according',
 'to',
 'an',
 'expert',
 'panel',
 'which',
 'gathered',
 'at',
 'annual',
 'consumer',
 'electronics',
 'show',
 'las',
 'vegas',
 'discuss',
 'how',
 'these',
 'new',
 'technologies',
 'impact',
 'one',
 'our',
 'favourite',
 'pastimes',
 'us',
 'leading',
 'trend',
 'programmes',
 'other',
 'content',
 'delivered',
 'via',
 'networks',
 'through',
 'cable',
 'satellite',
 'telecoms',
 'companies',
 'broadband',
 'service',
 'providers',
 'front',
 'rooms',
 'portable',
 'devices',
 'most',
 'talked-about',
 'ces',
 'has',
 'been',
 'personal',
 '(',
 'dvr',
 'pvr',
 ')',
 'set-top',
 'boxes',
 'like',
 's',
 'tivo',
 'uk',
 

In [ ]:
# number of documents
N = len(movies['text'])
N

2225

In [ ]:
# number of words (vocabulary size)
V = len(word2idx)
V

33990

In [ ]:
# instantiate term frequency matrix 
# although it would be more efficient to use a sparse matrix that makes things a bit more 
# complicated without improving your understanding.Thus, in this script, we will be using
# a dense matrix, which is just a regular Numpy array.
# note - could have used count vectorizer

tf = np.zeros((N,V))
tf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
for i, doc in enumerate(tokenized_docs):
#     print(doc)
    for j in doc:
        tf[i,j] += 1
#         print(j)

In [ ]:
tf

array([[12.,  2., 12., ...,  0.,  0.,  0.],
       [ 0.,  0.,  2., ...,  0.,  0.,  0.],
       [ 0.,  0.,  6., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  7., ...,  0.,  0.,  0.],
       [ 0.,  0., 10., ...,  1.,  1.,  0.],
       [ 0.,  1.,  6., ...,  0.,  0.,  1.]])

In [ ]:
# calculate IDF
document_freq = np.sum(tf>0, axis=0) #document_freq shape = (V,)
# note that if we call the some function with no arguments, it will just sum up the whole matrix into a single number
# And that number will be the number of ones in the whole matrix.Instead, we want to have the sum over each column or 
# equivalently the sum over each word.Therefore, we must specify axis equals zero.
# print(document_freq.shape)
idf = np.log(N / document_freq)
idf

array([2.39430622, 2.10539337, 0.00948302, ..., 7.70751219, 7.70751219,
       7.70751219])

In [ ]:
# compute tf-idf
tf_idf = tf * idf
tf_idf

array([[2.87316746e+01, 4.21078675e+00, 1.13796292e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.89660487e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.68981460e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 6.63811703e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 9.48302433e-02, ...,
        7.70751219e+00, 7.70751219e+00, 0.00000000e+00],
       [0.00000000e+00, 2.10539337e+00, 5.68981460e-02, ...,
        0.00000000e+00, 0.00000000e+00, 7.70751219e+00]])

In [ ]:
# random seed so that we get consistent results for the next portion of the notebook
np.random.seed(123)

In [ ]:
# choose random documents from our dataset and prints out the top five TF IDF terms.
# As you recall, our goal is to basically make sure that these makes sense in terms of what we expect tfidf to do
i = np.random.choice(N)
row = movies.iloc[i]
print('Category:', row['category'])
print('Text', row['text'].split(".",1)[0])
print('TOP 5 terms:')

scores = tf_idf[i]
indices = (-scores).argsort()

for j in indices[:5]:
    print(idx2word[j])




Category: tech
Text china  to overtake us net use  the chinese net-using population looks set to exceed that of the us in less than three years  says a report
TOP 5 terms:
makower
net
china
chinese
panlogic
